
- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927

- name: MongoDB | Add 10Gen repository
  shell:
    echo 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
    creates=/etc/apt/sources.list.d/mongodb-org-3.2.list

- name: MongoDB | Install latest MongoDB release
  apt: pkg=mongodb-org state=present update_cache=yes

- name: MongoDB | Insert hugepage disabled
  blockinfile:
    dest: /etc/init/mongod.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: "chown \\$DAEMONUSER /var/run/mongodb.pid"
    block: |2
        if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
          echo never > /sys/kernel/mm/transparent_hugepage/enabled
        fi
        if test -f /sys/kernel/mm/transparent_hugepage/defrag; then
          echo never > /sys/kernel/mm/transparent_hugepage/defrag
        fi
  notify:
    - restart mongo