
- name: download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
  become: yes

- name: install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  become: yes

- name: composer install
  composer: command=install working_dir={{ WEB_APPLICATION_ROOT_DIRECTORY }} optimize_autoloader={{ COMPOSER_OPTIMIZE_AUTOLOADER }} no_dev={{ COMPOSER_NO_DEV }}
  become: yes
  ignore_errors: true
